<table>
    <tr>
        <th>Search</th>
        <td><input type="text" name="fly-me-to-text"></td>
    </tr>
    <tr>
        <th>Type hint</th>
        <td>
            <input type="radio" name="fly-me-to-type" value="1" checked>Search for everything<br>
            <input type="radio" name="fly-me-to-type" value="2">Product<br>
            <input type="radio" name="fly-me-to-type" value="3">Category<br>
            <input type="radio" name="fly-me-to-type" value="4">Order<br>
            <input type="radio" name="fly-me-to-type" value="5">Customer<br>
        </td>
    </tr>
    <tr>
        <th>Destination</th>
        <td>
            <input type="radio" name="fly-me-to-destination" value="1" checked>Frontend<br>
            <input type="radio" name="fly-me-to-destination" value="2">Admin/backend<br>
        </td>
    </tr>
    <tr>
        <th>&nbsp;</th>
        <td>
            <input type="button" name="fly-me-to-button" value="Flight schedual" id="fly-me-to-button">
            <input type="button" name="fly-me-to-button" value="Direct flight" id="fly-me-directly-button">
        </td>
    </tr>
    <tr>
        <th>Resultset</th>
        <td>
            <div id="fly-me-to-results"></div>
        </td>
    </tr>
</table>